# yaml-language-server: $schema=https://app.stainlessapi.com/config.schema.json

organization:
    name: lumaai
    docs: https://lumalabs.ai
    contact: support+api@lumalabs.ai
resources:
    generations:
        methods:
            create: post /generations/video
            get: get /generations/{id}
            delete: delete /generations/{id}
            list:
                type: http
                endpoint: get /generations
                paginated: false
            upscale: post /generations/{id}/upscale
            audio: post /generations/{id}/audio
        subresources:
            concepts:
                methods:
                    list:
                        type: http
                        endpoint: get /generations/concepts/list
                        paginated: false
            image:
                methods:
                    create: post /generations/image
                    reframe: post /generations/image/reframe
            video:
                methods:
                    create: post /generations/video
                    reframe: post /generations/video/reframe

        models:
            generation: Generation
    ping:
        methods:
            check: get /ping
    credits:
        methods:
            get: get /credits
targets:
    node:
        package_name: lumaai
        production_repo: lumalabs/lumaai-node
        publish:
            npm: true
    python:
        package_name: lumaai
        production_repo: lumalabs/lumaai-python
        publish:
            pypi: true
settings:
    license: Apache-2.0
client_settings:
    opts:
        auth_token:
            type: string
            nullable: false
            read_env: LUMAAI_API_KEY
            auth: { security_scheme: BearerAuth }
environments:
    production: https://api.lumalabs.ai/dream-machine/v1
query_settings:
    nested_format: brackets
    array_format: comma
readme:
    example_requests:
        default:
            type: request
            endpoint: post /generations/video
            params:
                &ref_0 {
                    prompt: 'A teddy bear in sunglasses playing electric guitar, dancing and headbanging in the jungle in front of a large beautiful waterfall',
                    aspect_ratio: '16:9',
                    loop: false,
                    model: 'ray-2',
                }
        headline:
            type: request
            endpoint: post /generations/video
            params: *ref_0
    include_stainless_attribution: false

custom_casings:
    lumaai:
        pascal: LumaAI
        camel: lumaai
        snake: lumaai
        capital: LumaAI
# openapi:
#     code_samples: readme
