# yaml-language-server: $schema=https://app.stainlessapi.com/config.schema.json

organization:
    name: lumaai
    docs: https://lumalabs.ai
    contact: support@lumalabs.ai
resources:
    generations:
        methods:
            create: post /generations
            get: get /generations/{id}
            delete: delete /generations/{id}
            list:
                type: http
                endpoint: get /generations
                paginated: false
        subresources:
            camera_motion:
                methods:
                    list:
                        type: http
                        endpoint: get /generations/camera_motion/list
                        paginated: false
        models:
            generation: Generation
            camera_motion: CameraMotion
    ping:
        methods:
            check: get /ping
targets:
    node:
        package_name: lumaai
        production_repo: lumalabs/lumaai-node
        publish:
            npm: false
    python:
        package_name: lumaai
        production_repo: lumalabs/lumaai-python
        publish:
            pypi: false
settings:
    license: Apache-2.0
client_settings:
    opts:
        auth_token:
            type: string
            nullable: false
            auth: { security_scheme: BearerAuth }
environments:
    production: https://api.lumalabs.ai/dream-machine/v1alpha
query_settings:
    nested_format: brackets
    array_format: comma
readme:
    example_requests:
        default:
            type: request
            endpoint: post /generations
            params:
                &ref_0 {
                    prompt: 'A teddy bear in sunglasses playing electric guitar, dancing and headbanging in the jungle in front of a large beautiful waterfall',
                    aspect_ratio: '16:9',
                    loop: false,
                }
        headline:
            type: request
            endpoint: post /generations
            params: *ref_0
    include_stainless_attribution: false
