name: Upload OpenAPI spec to Stainless

on:
    push:
        branches: [main]

jobs:
    stainless:
        concurrency: upload-openapi-spec-action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: stainless-api/upload-openapi-spec-action@main
              with:
                  stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
                  input_path: 'openapi.yaml'
                  config_path: 'openapi.stainless.yml'
                  project_name: 'luma_ai'
            # - uses: readmeio/rdme@v8
            #   with:
            #       rdme: openapi "openapi.yaml" --key=${{ secrets.README_TOKEN }} --id=${{ secrets.README_DEFINITION_ID }}
